baseURL = "https://nsoft.vip"
languageCode = "zh-CN"
title = "疯狂的企鹅の网址导航"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author        = "crazyrico"
    description   = "疯狂的企鹅の网址导航"
    siteurl       = "./"
    about         = "http://www.nsoft.vip/about/"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"
    enablePreLoad = false		    		        # 网站完全打开前预加载的动画
    textPreLoad   = "疯狂的企鹅の网址导航"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    logosPath     = "assets/images/logos"				# 网站每个导航地址logo存放地址

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.ico"
    searchImageL      = ""		#搜索部分浅色背景图https://7ed.net/bing/api?rand=true&size=1024x768
    searchImageD      = "assets/images/search-bg-dark.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/bioitee-expand-light.png"
    logoExpandDark    = "assets/images/bioitee-expand-dark.png"
    logoCollapseLight = "assets/images/logo-collapse-light.png"
    logoCollapseDark  = "assets/images/logo-collapse-dark.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：crazyrico@qq.com <br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [疯狂的企鹅の导航](https://nsoft.vip/) | [苏ICP备17004952号-2](http://beian.miit.gov.cn/)<br/><span id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</span>'
